title: "Paysages à vélo"
baseline: "La boutique de cecillie."
baseurl: https://shop.cecillie.fr/
description: "Paysages à vélo, la boutique de cecillie."
author:
  name: studio cecillie
  url: https://studio.cecillie.fr
image: /images/default.png
languages:
  - code: fr-FR
    name: Français
    locale: fr_FR
language: fr-FR
menus:
  main:
    - id: index
      enabled: false
    - id: products
      enabled: false
  footer:
    - id: newsletter
      name: "Newsletter"
      url: https://mailchi.mp/a7fb0a1ad278/nl-shop-cecillie/
      weight: 3
    - id: twitter
      name: "Twitter"
      url: https://twitter.com/onibd
      weight: 4
    - id: instagram
      name: "Instagram"
      url: https://www.instagram.com/cecile.ricordeau/
      weight: 5
fonts:
  - url: https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap
  - url: https://fonts.googleapis.com/css2?family=Scope+One&display=swap
  - url: https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap
theme:
  - netlify
snipcart:
  version: 3.0.27
  apikey: ZTVlZWYzMTgtYjBkYS00MmE2LTgwNmYtMTcxZjliNWUxYjhmNjM3NDc0MzIyNTY4MjM5MzY2
  customer: true
#googleanalytics: 1234
netlify:
  redirects:
    - from: https://bikeeshop.netlify.com/*
      to: https://shop.cecillie.fr/:splat
      status: 301
      force: true
    #- from: https://shop.cecillie.fr/*
    #  to: https://mailchi.mp/a7fb0a1ad278/nl-shop-cecillie/
    #  status: 302
    #  force: true
