title: Paysages à vélo
baseline: La boutique de cecillie
baseurl: https://shop.cecillie.fr/
description: Illustrations de cyclistes, affiches et cartes en impression numérique de haute qualité. Les affiches sont toutes signées à la main par l'illustratrice.
author:
  name: cecillie
  url: https://cecillie.fr
image: images/cecillie_share_1200x628.jpg
menus:
  main:
    - id: index
      enabled: false
    - id: products
      enabled: false
  footer:
    #- id: newsletter
    #  name: Newsletter
    #  url: https://mailchi.mp/a7fb0a1ad278/nl-shop-cecillie/
    #  weight: 3
    - id: twitter
      name: Twitter
      url: https://twitter.com/onibd
      weight: 4
    - id: instagram
      name: Instagram
      url: https://www.instagram.com/cecile.ricordeau/
      weight: 5
language: fr-FR
languages:
  - code: fr-FR
    name: Français
    locale: fr_FR
  - code: en
    enabled: false
    name: English
    locale: en
    config:
      baseline: The shop of cecillie.
      description: Superb digital prints on premium semi matte coated paper 200g (A5 300g card). The posters are all hand signed.
      menus:
        main:
          - id: index
            enabled: false
          - id: products
            enabled: false
        footer:
          - id: instagram
            name: Instagram
            url: https://www.instagram.com/cecile.ricordeau/
            weight: 5
social:
  twitter:
    creator: onibd
pagination:
  enabled: false
static:
  load: true
fonts:
  - url: https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap
  - url: https://fonts.googleapis.com/css2?family=Scope+One&display=swap
  - url: https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap
theme:
  - netlify
  - netlify-cms
snipcart:
  version: 3.2.1
  apikey: ZTVlZWYzMTgtYjBkYS00MmE2LTgwNmYtMTcxZjliNWUxYjhmNjM3NDc0MzIyNTY4MjM5MzY2
  account: true
flickity:
  version: "2"
  fullscreen:
    version: "1"
cloudflareinsights: 5d643695e5b94058b6395c161f613653
webchat:
  enabled: false
  id: cc14b8df-44b8-4956-8ae2-1ea4e2f3d5a6
netlify:
  redirects:
    - from: https://bikeeshop.netlify.com/*
      to: https://shop.cecillie.fr/:splat
      status: "301"
      force: true
metatags:
  jsonld:
    enabled: true
body:
  images:
    caption:
      enabled: true
    resize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: false
assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
