[build]
  publish = "_site"
  command = "chmod +x ./scripts/netlify-build.sh && bash ./scripts/netlify-build.sh"

[build.environment]
  #PHP_VERSION = "7.4"

[context.production.environment]
  CECIL_ENV = "production"

[[context.production.plugins]]
  package = "netlify-plugin-cecil-cache"

[context.deploy-preview.environment]
  CECIL_ENV = "preview"
  CECIL_SNIPCART_APIKEY = "ZTVlZWYzMTgtYjBkYS00MmE2LTgwNmYtMTcxZjliNWUxYjhmNjM3NDc0MzIyNTY4MjM5MzY2"
