---
new_page_extension: md
auto_deploy: false
admin_path: "/static/cms"
webhook_url: 
sections:
- type: directory
  path: pages/products
  label: Produits
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - product
  - products
- type: heading
  label: Pages
- type: document
  path: pages/index.md
  label: Accueil
- type: document
  path: pages/le-projet.md
  label: Le projet
- type: document
  path: pages/contact.md
  label: Contact
- type: document
  path: pages/cgv.md
  label: CGV
- type: document
  path: pages/404.md
  label: Page 404
- type: heading
  label: Settings
- type: document
  path: config.yml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - PHP_VERSION=7.4
  preview_output_directory: _site
  install_dependencies_command: bash ./scripts/forestry-install.sh
  preview_docker_image: phpdocker/phpdocker:7.2
  mount_path: "/usr/src"
  working_dir: "/usr/src"
  instant_preview_command: php cecil.phar serve -v -d --host=0.0.0.0 --port=8080
