body:
  images:
    caption:
      enabled: false
    resize:
      enabled: false
    responsive:
      enabled: false
    webp:
      enabled: false
assets:
  images:
    optimize:
      enabled: false
    responsive:
      enabled: false
    webp:
      enabled: false
