---
label: Product
hide_body: false
display_field: name
fields:
- type: text
  name: name
  label: Name
  config:
    required: true
- type: text
  name: title
  label: Page title
- type: text
  name: description
  label: Description
- type: file
  name: image
  label: Image
- type: image_gallery
  name: gallery
  label: Gallery
- type: boolean
  name: published
  label: Published
