---
label: Products
hide_body: true
fields:
- type: field_group
  name: cascade
  label: Variables globales
  fields:
  - type: number
    name: price
    label: Prix
    description: Prix de référence.
    config:
      required: true
  - type: field_group_list
    name: variants
    label: Variants
    fields:
    - type: text
      name: name
      label: Nom
      config:
        required: true
    - type: field_group_list
      name: options
      label: Options
      fields:
      - type: text
        name: value
        label: Valeur
        config:
          required: true
      - type: text
        name: html
        label: HTML
        config:
          required: true
        description: Affichage dans la liste déroulante.
      - type: number
        name: price
        label: Prix
        config:
          required: true
        description: Prix relatif au prix de référence (peut être négatif).
      config:
        labelField: value
    config:
      labelField: name
  - type: number
    name: maxquantity
    label: Quantité max
    description: Quantité maximum autorisée lors de l'ajout au panier.
  - type: text
    name: stackable
    label: Empilable
    hidden: true
  hidden: false
pages:
- content/products/index.en.md
- content/products/index.md
