---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: name
  label: name
- type: file
  name: image
  label: image
- type: image_gallery
  name: gallery
  label: gallery
- type: boolean
  name: published
  label: published
