---
label: Product
hide_body: false
display_field: name
fields:
- type: text
  name: name
  label: Nom
  config:
    required: true
- type: text
  name: title
  label: Titre
  description: Titre de la page, différent du nom du produit.
- type: number
  name: price
  label: Prix
  config:
    required: true
  description: Prix de la variante de référence.
- type: file
  name: image
  label: Image
  description: Image de référence (également utilisée pour le partage sur les réseaux
    sociaux).
- type: image_gallery
  name: gallery
  label: Galerie
  description: Image complémentaire à l'image de référence.
- type: field_group_list
  name: variants
  label: Variantes
  fields:
  - type: text
    name: name
    label: Nom
    config:
      required: true
  - type: field_group_list
    name: options
    label: Options
    fields:
    - type: text
      name: value
      label: Valeur
      config:
        required: true
    - type: text
      name: html
      label: Affichage
      config:
        required: true
      description: Valeur affichée dans la liste.
    - type: number
      name: price
      label: Prix (relatif)
      description: 'Prix de l''option, relatif au prix de base (ex : "+5", "-10",
        "0", etc.).'
      config:
        required: true
    config:
      labelField: value
  config:
    labelField: name
- name: published
  type: boolean
  label: Publié
  default: false
