---
label: Products
hide_body: true
fields:
- type: field_group
  name: cascade
  label: Variables globales
  fields:
  - type: number
    name: price
    label: Prix
  - type: field_group_list
    name: variants
    label: Variants
    fields:
    - type: text
      name: name
      label: Nom
    - type: field_group_list
      name: options
      label: Options
      fields:
      - type: text
        name: value
        label: Valeur
      - type: text
        name: html
        label: HTML
      - type: number
        name: price
        label: Prix
  - type: number
    name: maxquantity
    label: Quantité max
  - type: text
    name: stackable
    label: Empilable
    hidden: true
  hidden: false
pages:
- content/products/index.md
