---
label: Product
hide_body: false
display_field: name
fields:
- type: text
  name: name
  label: Nom
  config:
    required: true
- type: text
  name: title
  label: Titre de la page
  config:
    required: true
- type: text
  name: description
  label: Description
  config:
    required: true
- type: file
  name: image
  label: Image
  description: Image principale.
- type: image_gallery
  name: gallery
  label: Galerie
  description: Images complémentaires.
- type: boolean
  name: published
  label: Publié
