---
label: Products section
hide_body: true
fields:
- type: field_group
  name: cascade
  label: Products default variables
  fields:
  - type: number
    name: price
    label: Price
    description: Prix de référence.
    config:
      required: true
  - type: field_group_list
    name: variants
    label: Variants
    fields:
    - type: text
      name: name
      label: Name
      config:
        required: true
    - type: field_group_list
      name: options
      label: Options
      fields:
      - type: text
        name: value
        label: Value
        config:
          required: true
      - type: text
        name: html
        label: HTML
        config:
          required: true
      - type: number
        name: price
        label: Price
        config:
          required: true
        default: 0
      config:
        labelField: value
    config:
      labelField: name
  hidden: false
pages:
- content/products/index.md
